// GENERATED from @smartico/public-api 0.0.434 — DO NOT EDIT.
// Regenerate: cd codegen && npm run gen

import Foundation

public struct SAWPrize: Codable, Hashable, Sendable {
    /// ID of the prize
    public var saw_prize_id: Int64?
    /// Visual definition of the prize (name, icon, win-modal buttons, per-game rendering hints)
    public var saw_prize_ui_definition: SAWPrizeUI?
    /// Numeric value for 'points' / 'spin' prize types (e.g. 100 for "100 points"); not relevant for other types
    public var prize_value: Double?
    /// The type of the prize — see {@link SAWPrizeType}
    public var prize_type_id: Int64?
    /// Competition games (MatchX / Quiz): first finishing place this prize applies to
    public var place_from: Double?
    /// Competition games (MatchX / Quiz): last finishing place this prize applies to; equals `place_from` for a single-place prize
    public var place_to: Double?
    /// Client-side only — unique id of a win instance generated by the default Smartico UI to dedupe render effects; never sent by the server
    public var sawUniqueWinId: String?
    /// Remaining stock. Present only when the template's `expose_game_stat_on_api` is enabled; always present for MatchX / Quiz games
    public var pool: Double?
    /// Initial (configured) stock. Present regardless of `expose_game_stat_on_api`
    public var pool_initial: Double?
    /// Times the prize has been won, across all players. Present only when `expose_game_stat_on_api` is enabled
    public var wins_count: Int64?
    /// ISO weekday numbers (1 = Monday … 7 = Sunday) the prize can be won on; absent = any day. Present only when `expose_game_stat_on_api` is enabled
    public var weekdays: [Int64]?
    /// Prize availability window start (epoch ms), evaluated against `relative_period_timezone`. Present only when `expose_game_stat_on_api` is enabled
    public var active_from_ts: Int64?
    /// Prize availability window end (epoch ms), evaluated against `relative_period_timezone`. Present only when `expose_game_stat_on_api` is enabled
    public var active_till_ts: Int64?
    /// Timezone offset in minutes for `weekdays` / active-window evaluation (UTC minus local)
    public var relative_period_timezone: Double?
    /// When true, the prize stays winnable at `pool` 0 (unlimited stock)
    public var is_surcharge: Bool?
    /// Always `false` in API responses — deleted prizes are excluded server-side
    public var is_deleted: Bool?
    /// Type-specific prize details — e.g. `gems` / `_gems_diamonds_type` for gems-and-diamonds prizes, `tickets_count` for raffle-ticket prizes
    public var prize_details_json: JSON?
    /// Period basis for the prize availability restriction — see {@link AttemptPeriodType}
    public var max_give_period_type_id: Int64?

    public init(
        saw_prize_id: Int64? = nil,
        saw_prize_ui_definition: SAWPrizeUI? = nil,
        prize_value: Double? = nil,
        prize_type_id: Int64? = nil,
        place_from: Double? = nil,
        place_to: Double? = nil,
        sawUniqueWinId: String? = nil,
        pool: Double? = nil,
        pool_initial: Double? = nil,
        wins_count: Int64? = nil,
        weekdays: [Int64]? = nil,
        active_from_ts: Int64? = nil,
        active_till_ts: Int64? = nil,
        relative_period_timezone: Double? = nil,
        is_surcharge: Bool? = nil,
        is_deleted: Bool? = nil,
        prize_details_json: JSON? = nil,
        max_give_period_type_id: Int64? = nil
    ) {
        self.saw_prize_id = saw_prize_id
        self.saw_prize_ui_definition = saw_prize_ui_definition
        self.prize_value = prize_value
        self.prize_type_id = prize_type_id
        self.place_from = place_from
        self.place_to = place_to
        self.sawUniqueWinId = sawUniqueWinId
        self.pool = pool
        self.pool_initial = pool_initial
        self.wins_count = wins_count
        self.weekdays = weekdays
        self.active_from_ts = active_from_ts
        self.active_till_ts = active_till_ts
        self.relative_period_timezone = relative_period_timezone
        self.is_surcharge = is_surcharge
        self.is_deleted = is_deleted
        self.prize_details_json = prize_details_json
        self.max_give_period_type_id = max_give_period_type_id
    }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: AnyCodingKey.self)
        self.saw_prize_id = try c.lenientInt64("saw_prize_id")
        self.saw_prize_ui_definition = try c.lenientObject(SAWPrizeUI.self, "saw_prize_ui_definition")
        self.prize_value = try c.lenientDouble("prize_value")
        self.prize_type_id = try c.lenientInt64("prize_type_id")
        self.place_from = try c.lenientDouble("place_from")
        self.place_to = try c.lenientDouble("place_to")
        self.sawUniqueWinId = try c.lenientString("sawUniqueWinId")
        self.pool = try c.lenientDouble("pool")
        self.pool_initial = try c.lenientDouble("pool_initial")
        self.wins_count = try c.lenientInt64("wins_count")
        self.weekdays = try c.lenientList(Int64.self, "weekdays")
        self.active_from_ts = try c.lenientInt64("active_from_ts")
        self.active_till_ts = try c.lenientInt64("active_till_ts")
        self.relative_period_timezone = try c.lenientDouble("relative_period_timezone")
        self.is_surcharge = try c.lenientBool("is_surcharge")
        self.is_deleted = try c.lenientBool("is_deleted")
        self.prize_details_json = try c.lenientJSON("prize_details_json")
        self.max_give_period_type_id = try c.lenientInt64("max_give_period_type_id")
    }
}
